/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.salusanalise.gerenciaconsultas.frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import br.com.salusanalise.gerenciaconsultas.dal.Conexao;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author Oberdran
 */
public class TelaDeExames extends javax.swing.JFrame {

    /**
     * Creates new form TelaExames
     */
    
    //informações sobre conexão
    Connection conexao = null;

     //executar instrucoes sql
    PreparedStatement pst = null;
    
    //executar instrucoes sql
    ResultSet rs = null;
    
    
    public TelaDeExames() {
        initComponents();
        
        //informações para poder salvar no banco            
            conexao = Conexao.conector();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeExame = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDtAtendimentoExame = new javax.swing.JTextField();
        txtDtEntregaExame = new javax.swing.JTextField();
        btnSalvarExame = new javax.swing.JButton();
        btnSairTelaExame = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObervacaoExame = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exames");
        setResizable(false);

        jLabel1.setText("PACIENTE:");

        btnPesquisarNome.setText("Pesquisar");
        btnPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("EXAME:");

        txtNomeExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeExameActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Entrega:");

        jLabel4.setText("Data do Atendimento:");

        txtDtAtendimentoExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtAtendimentoExameActionPerformed(evt);
            }
        });

        txtDtEntregaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtEntregaExameActionPerformed(evt);
            }
        });

        btnSalvarExame.setText("Salvar");
        btnSalvarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarExameActionPerformed(evt);
            }
        });

        btnSairTelaExame.setText("Sair");
        btnSairTelaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairTelaExameActionPerformed(evt);
            }
        });

        txtAreaObervacaoExame.setColumns(20);
        txtAreaObervacaoExame.setRows(5);
        jScrollPane1.setViewportView(txtAreaObervacaoExame);

        jLabel5.setText("Observação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(btnSalvarExame)
        							.addPreferredGap(ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
        							.addComponent(btnSairTelaExame))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel2)
        								.addComponent(jLabel1))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(txtNomePaciente, GroupLayout.PREFERRED_SIZE, 202, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
        									.addComponent(btnPesquisarNome))
        								.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        									.addComponent(txtNomeExame, Alignment.LEADING)
        									.addComponent(jScrollPane1, Alignment.LEADING))))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addGap(3)
        							.addComponent(txtDtAtendimentoExame, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jLabel3)
        							.addGap(3)
        							.addComponent(txtDtEntregaExame, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)))
        					.addGap(27))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel5)
        					.addContainerGap(347, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtNomePaciente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnPesquisarNome)
        				.addComponent(jLabel1))
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtNomeExame, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addPreferredGap(ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
        			.addComponent(jLabel5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txtDtAtendimentoExame, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel3)
        					.addComponent(txtDtEntregaExame, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jLabel4))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnSalvarExame)
        				.addComponent(btnSairTelaExame))
        			.addGap(19))
        );
        getContentPane().setLayout(layout);

        setSize(new java.awt.Dimension(441, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeExameActionPerformed

    private void txtDtAtendimentoExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtAtendimentoExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtAtendimentoExameActionPerformed

    private void txtDtEntregaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtEntregaExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtEntregaExameActionPerformed

    private void btnSalvarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarExameActionPerformed
        // TODO add your handling code here:
        
        salvarExamePaciente();
    }//GEN-LAST:event_btnSalvarExameActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed
        // TODO add your handling code here:
        
        if(txtNomePaciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o nome do Paciente!");
        }else{
            buscarNomePaciente();
        }

    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void btnSairTelaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTelaExameActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnSairTelaExameActionPerformed

        
    public void limparCampos(){
        txtNomePaciente.setText("");
        txtNomeExame.setText("");
        txtAreaObervacaoExame.setText("");
        txtDtAtendimentoExame.setText("");
        txtDtEntregaExame.setText("");
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeExames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnSairTelaExame;
    private javax.swing.JButton btnSalvarExame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaObervacaoExame;
    private javax.swing.JTextField txtDtAtendimentoExame;
    private javax.swing.JTextField txtDtEntregaExame;
    private javax.swing.JTextField txtNomeExame;
    private javax.swing.JTextField txtNomePaciente;
    // End of variables declaration//GEN-END:variables


       
    private void salvarExamePaciente(){
        String sql = "insert into atendimento_paciente (nome_paciente,exame,observ,dtatendimento,dtentregaexame)values(?,?,?,?,?)";
   
        try {
            
            pst = conexao.prepareStatement(sql);
            
            //pegar o conteúdo dos campos 
            //esse numero, significa a ordem de inserção com os campos passados
            //na string
            
            //dados paciente
            pst.setString(1, txtNomePaciente.getText());
            
            
            
            //dados exames
            pst.setString(2, txtNomeExame.getText());
           
            pst.setString(3, txtAreaObervacaoExame.getText());
            
            
            //dados exames
            
            pst.setString(4, txtDtAtendimentoExame.getText());
            
            pst.setString(5, txtDtEntregaExame.getText());
            
           
            //a linha abaixo atualiza a tabela usuario com os dados do formulario
            //confirmar se os dados foram salvos
            
            int add = pst.executeUpdate();
            
            if(add >0){
                JOptionPane.showMessageDialog(null, "Cadastro realizado!");
            
                limparCampos();
            }
            
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null, e);
        }
    
    }

        
    private void buscarNomePaciente(){
        
        //fazendo busca no banco passando o nome na hr da busca, por isso o like na consulta
        String sql = "select nome from paciente where nome like ?";
   
        try {
            
            pst = conexao.prepareStatement(sql);
           
            //desse jeito abaixo ele pega as informações passada no campo e concatena junto a string sql
            pst.setString(1, "%"+txtNomePaciente.getText()+"%");
            
           //depois de alimentar o ponto de interrogação
           
            rs = pst.executeQuery();
           
         
            if(rs.next()){
                
                // esse metodo next() diz se existe o proximo, ele vai pegar a informação do campo 1, que
                //é o campo nome, começa do 0 zero
                txtNomePaciente.setText(rs.getString(1));
   
            }else{
                //caso não encontre aparece a mensagem abaixo e limpa o campo
                //para não confundi o usuário do sistema
                
                JOptionPane.showMessageDialog(null, "Paciente não localizado");
                txtNomePaciente.setText("");
            }
            
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
}
