/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.salusanalise.gerenciaconsultas.frame;

import br.com.salusanalise.gerenciaconsultas.dal.Conexao;
import java.sql.*;

import javax.swing.JOptionPane;


/**
 *
 * @author Oberdran
 */
public class TelaLogin extends javax.swing.JFrame {

    Connection conexao = null;

     //executar instrucoes sql
    PreparedStatement pst = null;
    
    //executar instrucoes sql
    ResultSet rs = null;
    
    public void logar (){
        
        //INSERT INTO usuariosclinica VALUES(1,'admin','administrador','clinica2020')
        
        String sql = "select * from usuariosclinica where login = ? and senha = ?";
        try {
            //as linhas abaixo preparam a consulta ao banco em função
            //do que foi digitado nas caixas de texto. O ? é substituído
            //pelo conteúdo das variáveis
            
            pst = conexao.prepareStatement(sql);
            
            //pegando os valores dos campos de texto
            pst.setString(1, txtUsuarioLogin.getText());
            pst.setString(2, txtCmpSenhaLogin.getText());
            
            //a linha abaixo executa a query
            rs = pst.executeQuery();
            
            //verificando se o usuario e senha correspondente
            if(rs.next()){
                
                System.out.println("logado no sistema");
            
                TelaDeMenu tm = new TelaDeMenu();
                tm.setVisible(true);
                
                //fechando a tela de login
                this.dispose();
                
                //fechando a conexao da tela de login com o banco
                conexao.close();
                
            }else{
                
                JOptionPane.showMessageDialog(null,"Usuário e/ou Senha inválido(s)");
            }
            
        } catch (Exception e) {
        }
    }
    
    public void logarBancoJuntoAplicacao (){
        
        //INSERT INTO usuariosclinica VALUES(1,'admin','administrador','clinica2020')
        
        String sql = "select * from root.usuariosclinica where login = ? and senha = ?";
        try {
            //as linhas abaixo preparam a consulta ao banco em função
            //do que foi digitado nas caixas de texto. O ? é substituído
            //pelo conteúdo das variáveis
            
            pst = conexao.prepareStatement(sql);
            
            //pegando os valores dos campos de texto
            pst.setString(1, txtUsuarioLogin.getText());
            pst.setString(2, txtCmpSenhaLogin.getText());
            
            //a linha abaixo executa a query
            rs = pst.executeQuery();
            
            //verificando se o usuario e senha correspondente
            if(rs.next()){
                
                System.out.println("logado no sistema - Banco Derby");
            
                TelaDeMenu tm = new TelaDeMenu();
                tm.setVisible(true);
                
                //fechando a tela de login
                this.dispose();
                
                //fechando a conexao da tela de login com o banco
                conexao.close();
                
            }else{
                
                JOptionPane.showMessageDialog(null,"Usuário e/ou Senha inválido(s)");
            }
            
        } catch (Exception e) {
        }
    }
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        
        conexao = Conexao.conector();
        
        System.out.println(conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        btnLoginSistema = new javax.swing.JButton();
        txtCmpSenhaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso");
        setResizable(false);

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        txtUsuarioLogin.setName("txtUsuario"); // NOI18N

        btnLoginSistema.setText("Login");
        btnLoginSistema.setName("btnLogin"); // NOI18N
        btnLoginSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSistemaActionPerformed(evt);
            }
        });

        txtCmpSenhaLogin.setName("cmpSenha"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoginSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtCmpSenhaLogin))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCmpSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnLoginSistema)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(317, 269));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            //logar();
            
            //logando no banco que roda junto com a aplicação
            logarBancoJuntoAplicacao ();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtCmpSenhaLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
